# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int2bin <- function(n) {
    .Call('_scfind_int2bin', PACKAGE = 'scfind', n)
}

eliasFanoCoding <- function(inds_list, l) {
    .Call('_scfind_eliasFanoCoding', PACKAGE = 'scfind', inds_list, l)
}

eliasFanoDecoding <- function(H, L, l) {
    .Call('_scfind_eliasFanoDecoding', PACKAGE = 'scfind', H, L, l)
}

