# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quantizeCpp <- function(ids, n) {
    .Call('_scfind_quantizeCpp', PACKAGE = 'scfind', ids, n)
}

intersect_cells <- function(a, b) {
    .Call('_scfind_intersect_cells', PACKAGE = 'scfind', a, b)
}

eliasFanoCodingCpp <- function(expression_vector) {
    .Call('_scfind_eliasFanoCodingCpp', PACKAGE = 'scfind', expression_vector)
}

eliasFanoDecodingCpp <- function(H, L, l) {
    .Call('_scfind_eliasFanoDecodingCpp', PACKAGE = 'scfind', H, L, l)
}

