# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


setRcppClass("EliasFanoDB", module = "EliasFanoDB")


#' @export
EliasFano <- function()
{
    .Call("_rcpp_module_boot_EliasFanoDB", PACKAGE = "scfind")
}


loadModule("EliasFanoDB", TRUE)
